### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by maheshauti96** [maheshauti96/vidyartha-app#9]
- [x] 1. overlay - model when we land on shared link - Prathamesh
- [x] 2. footer - Vishal
- [x] 3. bug on selecting a school
- [x] 4. if top doners are present, then show the list - siddhi to populate, Mahesh will provide the design.
- [x] 5. about fund raiser campain - Vishal
- [ ] 6. search fields in header on payment page - Siddhi, , Mahesh will provide the design.
- [ ] 7. home page input fields and other design revisit (Mahesh)
